PROJECTS_DIR="${HOME}/Projects"
TOOLS_DIR="${HOME}/Projects/Tools"
CODE_DIR="${HOME}/Projects/Code"
DOTFILES_DIR="${HOME}/Projects/Tools/dotfiles"

# Path to your oh-my-zsh installation.
export ZSH=$HOME/.oh-my-zsh

# Install theme
ZSH_THEME="bira"