function sourceIfPossible() {
    if [[ -r $1 ]]; then
        source $1
    fi
}

# Path to your oh-my-zsh installation.
export ZSH=$HOME/.oh-my-zsh

# Install theme
ZSH_THEME="bira"

# Make completion consider case
CASE_SENSITIVE="true"

# Allow oh-my-zsh to automatically update
DISABLE_UPDATE_PROMPT="true"

# Enable plugins. The format in plugins=(plugin1 plugin2 ...)
# - command-not-found: Provides useful msg on install command on ubuntu
# - npm: Provides auto-complete for NPM commands
plugins=(command-not-found npm)

# This forces ZSH to use a user directory
mkdir -p $HOME/.zsh
ZSH_CACHE_DIR=$HOME/.zsh

# Start oh-my-zsh...
source $ZSH/oh-my-zsh.sh

# Add custom terminal setup
source "${HOME}/Projects/Tools/dotfiles/assets/terminal-profile"

# Add NPM-Packages directory
export NPM_PACKAGES="${HOME}/.npm-packages"
export NODE_PATH="$NPM_PACKAGES/lib/node_modules${NODE_PATH:+:$NODE_PATH}"
export PATH="$NPM_PACKAGES/bin:$PATH"

# Load corp dotfiles if they exist
sourceIfPossible("${HOME}/Projects/Tools/corp-dotfiles/assets/corp.zshrc")